### ISSUE TITLE
Is there a way to get multiple channels by ID in a single query?

### ISSUE THREAD

**Issue by siffring** [objectivehtml/Channel-Data#4]
Hi,

I'm trying to get a handful of channels by ID. 

e.g. SELECT \* FROM channels WHERE id IN (1, 2, 3);

It's not clear to me if the format for the WHERE clauses in this API support that.

``` php
$channels = $this->EE->channel_data->get_channels( array(
            'where' => array(
                'channels.channel_id' => 1,
                'OR channels.channel_id' => 2,
                'OR channels.channel_id' => 3
            )
        ))->result_array();
```

Since the second and third items in my WHERE array are the same on the left, the first one gets over written. Here's the query that gets executed:

```
SELECT *
FROM (`exp_channels`)
WHERE  (`exp_channels`.`channel_id` = 1) OR (`exp_channels`.`channel_id` = 3)
ORDER BY `channel_id` DESC 
```

The IN method doesn't seem to work either:

``` php
$channels = $this->EE->channel_data->get_channels( array(
            'where' => array(
                'channels.channel_id IN' => "1, 2, 3"
            )
        ))->result_array();
```

This generates a SQL syntax error:

```
SELECT * FROM (`exp_channels`) WHERE (`exp_channels`.`channel_id` IN = '1, 2, 3') ORDER BY `channel_id` DESC
```

Is there an easier way to do this short of running get_channel() three times?

I'm willing to add support for IN and send a pull request if you think that's the right approach.

I'm using the latest dev branch btw.

**Comment by objectivehtml** [comment]
There are two ways to do this:

```
$this->EE->channel_data->get_channels(array(
    'where' => array(
        'channels.channel_id' => array(
             '1',
             'or 2',
             'or 3',
        )
    )
));

$this->EE->channel_data->get_channels(array(
    'where' => array(
        'channels.channel_id' => '1',
        '{1} or channels.channel_id' => '2',
        '{2} or channels.channel_id' => '3',
    )
));
```

The latter syntax was the original way I solved the problem, then later I added the first syntax I listed.

**Comment by siffring** [comment]
That worked. Thanks!
